name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            merge
            feat
            chore
            perf
            ci
            ops
            build
            docs
            style
            rollback
            refactor
            test

          scopes: |
            deployment/skaffold
            deployment/cluster

            core

            api-gateway
            monitor-server

            auth-service
            forum-service

          requireScope: false
          disallowScopes: |
            release
            [A-Z]+
